# Generated by Django 6.0.3 on 2026-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('In progress', 'In progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
