# Generated by Django 6.0.3 on 2026-05-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('In progress', 'In progress'), ('done', 'Done')], max_length=20),
        ),
    ]
