# Generated by Django 6.0.3 on 2026-05-21 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('task_completed', 'Task completed'), ('task_overdue', 'Task overdue'), ('comment_added', 'Comment added'), ('status_changed', 'Status changed'), ('invitation_sent', 'Invitation sent'), ('project_joined', 'Project joined')], max_length=50),
        ),
    ]
