# Generated by Django 6.0.3 on 2026-05-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_project_alter_notification_task_and_more'),
        ('tasks', '0005_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='project',
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('task_completed', 'Task completed'), ('task_overdue', 'Task overdue'), ('comment_added', 'Comment added')], max_length=50),
        ),
    ]
