/// Tłumaczenia dla całej aplikacji — 15 języków.
class AppStrings {
  final String _code;
  AppStrings._(this._code);

  factory AppStrings.of(String code) =>
      AppStrings._(_translations.containsKey(code) ? code : 'en');

  String _t(String key) =>
      _translations[_code]?[key] ?? _translations['en']![key] ?? key;

  // ── Nawigacja dolna ───────────────────────────────────────────────────────
  String get navHome => _t('navHome');
  String get navProjects => _t('navProjects');
  String get navCalendar => _t('navCalendar');
  String get navAccount => _t('navAccount');

  // ── Ekran główny ──────────────────────────────────────────────────────────
  String get hey => _t('hey');
  String get checkTasksToday => _t('checkTasksToday');
  String get searchTasks => _t('searchTasks');
  String get myProjects => _t('myProjects');
  String get seeAll => _t('seeAll');
  String get myTasks => _t('myTasks');
  String get noTasksAssigned => _t('noTasksAssigned');
  String get noTasksAssignedDesc => _t('noTasksAssignedDesc');
  String get createFirstProject => _t('createFirstProject');
  String get tapToStart => _t('tapToStart');
  String get firstCreateProject => _t('firstCreateProject');
  String get selectProject => _t('selectProject');

  // ── Projekty ──────────────────────────────────────────────────────────────
  String get projects => _t('projects');
  String get newProject => _t('newProject');
  String get projectName => _t('projectName');
  String get descriptionOptional => _t('descriptionOptional');
  String get addMembers => _t('addMembers');
  String get noUsersAvailable => _t('noUsersAvailable');
  String get create => _t('create');
  String get noProjects => _t('noProjects');
  String get createFirstProjectDesc => _t('createFirstProjectDesc');

  // ── Kalendarz ─────────────────────────────────────────────────────────────
  String get calendar => _t('calendar');
  String get noTasksForDay => _t('noTasksForDay');
  String get tasksFor => _t('tasksFor');

  // ── Profil ────────────────────────────────────────────────────────────────
  String get profileData => _t('profileData');
  String get edit => _t('edit');
  String get cancel => _t('cancel');
  String get saveChanges => _t('saveChanges');
  String get username => _t('username');
  String get email => _t('email');
  String get administrator => _t('administrator');
  String get profileUpdated => _t('profileUpdated');
  String get errorSaving => _t('errorSaving');
  String get notifications => _t('notifications');
  String get notifMentions => _t('notifMentions');
  String get notifMentionsDesc => _t('notifMentionsDesc');
  String get notifNewTasks => _t('notifNewTasks');
  String get notifNewTasksDesc => _t('notifNewTasksDesc');
  String get notifStatusChanges => _t('notifStatusChanges');
  String get notifStatusChangesDesc => _t('notifStatusChangesDesc');
  String get language => _t('language');
  String get selectLanguage => _t('selectLanguage');
  String get changePassword => _t('changePassword');
  String get logout => _t('logout');

  // ──────────────────────────────────────────────────────────────────────────
  static const _translations = <String, Map<String, String>>{
    // ── Polski ───────────────────────────────────────────────────────────────
    'pl': {
      'navHome': 'Home', 'navProjects': 'Projekty',
      'navCalendar': 'Kalendarz', 'navAccount': 'Konto',
      'hey': 'Hej,', 'checkTasksToday': 'Sprawdź swoje zadania na dziś',
      'searchTasks': 'Szukaj zadań…', 'myProjects': 'Moje projekty',
      'seeAll': 'Zobacz wszystkie', 'myTasks': 'Moje zadania',
      'noTasksAssigned': 'Brak przypisanych zadań',
      'noTasksAssignedDesc': 'Zadania przypisane do Ciebie pojawią się tutaj',
      'createFirstProject': 'Utwórz pierwszy projekt',
      'tapToStart': 'Dotknij, aby zacząć',
      'firstCreateProject': 'Najpierw utwórz projekt',
      'selectProject': 'Wybierz projekt',
      'projects': 'Projekty', 'newProject': 'Nowy projekt',
      'projectName': 'Nazwa projektu', 'descriptionOptional': 'Opis (opcjonalnie)',
      'addMembers': 'Dodaj członków',
      'noUsersAvailable': 'Brak dostępnych użytkowników',
      'create': 'Utwórz', 'noProjects': 'Brak projektów',
      'createFirstProjectDesc': 'Utwórz swój pierwszy projekt',
      'calendar': 'Kalendarz', 'noTasksForDay': 'Brak zadań na ten dzień',
      'tasksFor': 'Zadania na',
      'profileData': 'Dane profilu', 'edit': 'Edytuj', 'cancel': 'Anuluj',
      'saveChanges': 'Zapisz zmiany', 'username': 'Nazwa użytkownika',
      'email': 'E-mail', 'administrator': 'Administrator',
      'profileUpdated': 'Profil zaktualizowany', 'errorSaving': 'Błąd zapisywania',
      'notifications': 'Powiadomienia', 'notifMentions': 'Wzmianki',
      'notifMentionsDesc': 'Gdy ktoś Cię wspomni',
      'notifNewTasks': 'Nowe zadania',
      'notifNewTasksDesc': 'Gdy zostaniesz przypisany do zadania',
      'notifStatusChanges': 'Zmiany statusu',
      'notifStatusChangesDesc': 'Gdy status zadania się zmieni',
      'language': 'Język', 'selectLanguage': 'Wybierz język',
      'changePassword': 'Zmień hasło', 'logout': 'Wyloguj się',
    },
    // ── English ──────────────────────────────────────────────────────────────
    'en': {
      'navHome': 'Home', 'navProjects': 'Projects',
      'navCalendar': 'Calendar', 'navAccount': 'Account',
      'hey': 'Hey,', 'checkTasksToday': 'Check your tasks for today',
      'searchTasks': 'Search tasks…', 'myProjects': 'My projects',
      'seeAll': 'See all', 'myTasks': 'My tasks',
      'noTasksAssigned': 'No assigned tasks',
      'noTasksAssignedDesc': 'Tasks assigned to you will appear here',
      'createFirstProject': 'Create your first project',
      'tapToStart': 'Tap to start',
      'firstCreateProject': 'Create a project first',
      'selectProject': 'Select project',
      'projects': 'Projects', 'newProject': 'New project',
      'projectName': 'Project name', 'descriptionOptional': 'Description (optional)',
      'addMembers': 'Add members', 'noUsersAvailable': 'No users available',
      'create': 'Create', 'noProjects': 'No projects',
      'createFirstProjectDesc': 'Create your first project',
      'calendar': 'Calendar', 'noTasksForDay': 'No tasks for this day',
      'tasksFor': 'Tasks for',
      'profileData': 'Profile Data', 'edit': 'Edit', 'cancel': 'Cancel',
      'saveChanges': 'Save Changes', 'username': 'Username', 'email': 'Email',
      'administrator': 'Administrator', 'profileUpdated': 'Profile updated',
      'errorSaving': 'Error saving profile', 'notifications': 'Notifications',
      'notifMentions': 'Mentions', 'notifMentionsDesc': 'When someone mentions you',
      'notifNewTasks': 'New Tasks',
      'notifNewTasksDesc': 'When you are assigned to a task',
      'notifStatusChanges': 'Status Changes',
      'notifStatusChangesDesc': 'When a task status changes',
      'language': 'Language', 'selectLanguage': 'Select Language',
      'changePassword': 'Change Password', 'logout': 'Log Out',
    },
    // ── Deutsch ──────────────────────────────────────────────────────────────
    'de': {
      'navHome': 'Home', 'navProjects': 'Projekte',
      'navCalendar': 'Kalender', 'navAccount': 'Konto',
      'hey': 'Hallo,',
      'checkTasksToday': 'Überprüfen Sie Ihre Aufgaben für heute',
      'searchTasks': 'Aufgaben suchen…', 'myProjects': 'Meine Projekte',
      'seeAll': 'Alle anzeigen', 'myTasks': 'Meine Aufgaben',
      'noTasksAssigned': 'Keine zugewiesenen Aufgaben',
      'noTasksAssignedDesc': 'Ihnen zugewiesene Aufgaben erscheinen hier',
      'createFirstProject': 'Erstes Projekt erstellen',
      'tapToStart': 'Tippen zum Starten',
      'firstCreateProject': 'Erstellen Sie zuerst ein Projekt',
      'selectProject': 'Projekt auswählen',
      'projects': 'Projekte', 'newProject': 'Neues Projekt',
      'projectName': 'Projektname',
      'descriptionOptional': 'Beschreibung (optional)',
      'addMembers': 'Mitglieder hinzufügen',
      'noUsersAvailable': 'Keine Benutzer verfügbar',
      'create': 'Erstellen', 'noProjects': 'Keine Projekte',
      'createFirstProjectDesc': 'Erstellen Sie Ihr erstes Projekt',
      'calendar': 'Kalender',
      'noTasksForDay': 'Keine Aufgaben für diesen Tag',
      'tasksFor': 'Aufgaben für',
      'profileData': 'Profildaten', 'edit': 'Bearbeiten',
      'cancel': 'Abbrechen', 'saveChanges': 'Änderungen speichern',
      'username': 'Benutzername', 'email': 'E-Mail',
      'administrator': 'Administrator', 'profileUpdated': 'Profil aktualisiert',
      'errorSaving': 'Fehler beim Speichern',
      'notifications': 'Benachrichtigungen', 'notifMentions': 'Erwähnungen',
      'notifMentionsDesc': 'Wenn jemand Sie erwähnt',
      'notifNewTasks': 'Neue Aufgaben',
      'notifNewTasksDesc': 'Wenn Sie einer Aufgabe zugewiesen werden',
      'notifStatusChanges': 'Statusänderungen',
      'notifStatusChangesDesc': 'Wenn sich der Status einer Aufgabe ändert',
      'language': 'Sprache', 'selectLanguage': 'Sprache auswählen',
      'changePassword': 'Passwort ändern', 'logout': 'Abmelden',
    },
    // ── Français ─────────────────────────────────────────────────────────────
    'fr': {
      'navHome': 'Accueil', 'navProjects': 'Projets',
      'navCalendar': 'Calendrier', 'navAccount': 'Compte',
      'hey': 'Salut,',
      'checkTasksToday': "Vérifiez vos tâches pour aujourd'hui",
      'searchTasks': 'Rechercher des tâches…', 'myProjects': 'Mes projets',
      'seeAll': 'Voir tout', 'myTasks': 'Mes tâches',
      'noTasksAssigned': 'Aucune tâche assignée',
      'noTasksAssignedDesc': 'Les tâches assignées apparaîtront ici',
      'createFirstProject': 'Créer votre premier projet',
      'tapToStart': 'Touchez pour commencer',
      'firstCreateProject': "Créez d'abord un projet",
      'selectProject': 'Sélectionner un projet',
      'projects': 'Projets', 'newProject': 'Nouveau projet',
      'projectName': 'Nom du projet',
      'descriptionOptional': 'Description (optionnel)',
      'addMembers': 'Ajouter des membres',
      'noUsersAvailable': 'Aucun utilisateur disponible',
      'create': 'Créer', 'noProjects': 'Aucun projet',
      'createFirstProjectDesc': 'Créez votre premier projet',
      'calendar': 'Calendrier',
      'noTasksForDay': 'Aucune tâche pour ce jour',
      'tasksFor': 'Tâches pour',
      'profileData': 'Données du profil', 'edit': 'Modifier',
      'cancel': 'Annuler',
      'saveChanges': 'Enregistrer les modifications',
      'username': "Nom d'utilisateur", 'email': 'E-mail',
      'administrator': 'Administrateur', 'profileUpdated': 'Profil mis à jour',
      'errorSaving': 'Erreur lors de la sauvegarde',
      'notifications': 'Notifications', 'notifMentions': 'Mentions',
      'notifMentionsDesc': "Quand quelqu'un vous mentionne",
      'notifNewTasks': 'Nouvelles tâches',
      'notifNewTasksDesc': 'Quand vous êtes assigné à une tâche',
      'notifStatusChanges': 'Changements de statut',
      'notifStatusChangesDesc': "Quand le statut d'une tâche change",
      'language': 'Langue', 'selectLanguage': 'Choisir la langue',
      'changePassword': 'Changer le mot de passe',
      'logout': 'Se déconnecter',
    },
    // ── Español ──────────────────────────────────────────────────────────────
    'es': {
      'navHome': 'Inicio', 'navProjects': 'Proyectos',
      'navCalendar': 'Calendario', 'navAccount': 'Cuenta',
      'hey': '¡Hola,', 'checkTasksToday': 'Revisa tus tareas de hoy',
      'searchTasks': 'Buscar tareas…', 'myProjects': 'Mis proyectos',
      'seeAll': 'Ver todos', 'myTasks': 'Mis tareas',
      'noTasksAssigned': 'Sin tareas asignadas',
      'noTasksAssignedDesc': 'Las tareas asignadas a ti aparecerán aquí',
      'createFirstProject': 'Crea tu primer proyecto',
      'tapToStart': 'Toca para empezar',
      'firstCreateProject': 'Primero crea un proyecto',
      'selectProject': 'Seleccionar proyecto',
      'projects': 'Proyectos', 'newProject': 'Nuevo proyecto',
      'projectName': 'Nombre del proyecto',
      'descriptionOptional': 'Descripción (opcional)',
      'addMembers': 'Agregar miembros',
      'noUsersAvailable': 'No hay usuarios disponibles',
      'create': 'Crear', 'noProjects': 'Sin proyectos',
      'createFirstProjectDesc': 'Crea tu primer proyecto',
      'calendar': 'Calendario',
      'noTasksForDay': 'Sin tareas para este día',
      'tasksFor': 'Tareas para',
      'profileData': 'Datos del perfil', 'edit': 'Editar',
      'cancel': 'Cancelar', 'saveChanges': 'Guardar cambios',
      'username': 'Nombre de usuario', 'email': 'Correo electrónico',
      'administrator': 'Administrador', 'profileUpdated': 'Perfil actualizado',
      'errorSaving': 'Error al guardar', 'notifications': 'Notificaciones',
      'notifMentions': 'Menciones',
      'notifMentionsDesc': 'Cuando alguien te mencione',
      'notifNewTasks': 'Nuevas tareas',
      'notifNewTasksDesc': 'Cuando te asignen a una tarea',
      'notifStatusChanges': 'Cambios de estado',
      'notifStatusChangesDesc': 'Cuando cambie el estado de una tarea',
      'language': 'Idioma', 'selectLanguage': 'Seleccionar idioma',
      'changePassword': 'Cambiar contraseña', 'logout': 'Cerrar sesión',
    },
    // ── Italiano ─────────────────────────────────────────────────────────────
    'it': {
      'navHome': 'Home', 'navProjects': 'Progetti',
      'navCalendar': 'Calendario', 'navAccount': 'Account',
      'hey': 'Ciao,', 'checkTasksToday': 'Controlla i tuoi compiti di oggi',
      'searchTasks': 'Cerca compiti…', 'myProjects': 'I miei progetti',
      'seeAll': 'Vedi tutti', 'myTasks': 'I miei compiti',
      'noTasksAssigned': 'Nessun compito assegnato',
      'noTasksAssignedDesc': 'I compiti assegnati a te appariranno qui',
      'createFirstProject': 'Crea il tuo primo progetto',
      'tapToStart': 'Tocca per iniziare',
      'firstCreateProject': 'Prima crea un progetto',
      'selectProject': 'Seleziona progetto',
      'projects': 'Progetti', 'newProject': 'Nuovo progetto',
      'projectName': 'Nome del progetto',
      'descriptionOptional': 'Descrizione (opzionale)',
      'addMembers': 'Aggiungi membri',
      'noUsersAvailable': 'Nessun utente disponibile',
      'create': 'Crea', 'noProjects': 'Nessun progetto',
      'createFirstProjectDesc': 'Crea il tuo primo progetto',
      'calendar': 'Calendario',
      'noTasksForDay': 'Nessun compito per questo giorno',
      'tasksFor': 'Compiti per',
      'profileData': 'Dati del profilo', 'edit': 'Modifica',
      'cancel': 'Annulla', 'saveChanges': 'Salva modifiche',
      'username': 'Nome utente', 'email': 'E-mail',
      'administrator': 'Amministratore', 'profileUpdated': 'Profilo aggiornato',
      'errorSaving': 'Errore nel salvataggio',
      'notifications': 'Notifiche', 'notifMentions': 'Menzioni',
      'notifMentionsDesc': 'Quando qualcuno ti menziona',
      'notifNewTasks': 'Nuovi compiti',
      'notifNewTasksDesc': 'Quando vieni assegnato a un compito',
      'notifStatusChanges': 'Cambi di stato',
      'notifStatusChangesDesc': 'Quando lo stato di un compito cambia',
      'language': 'Lingua', 'selectLanguage': 'Seleziona lingua',
      'changePassword': 'Cambia password', 'logout': 'Esci',
    },
    // ── Português ────────────────────────────────────────────────────────────
    'pt': {
      'navHome': 'Início', 'navProjects': 'Projetos',
      'navCalendar': 'Calendário', 'navAccount': 'Conta',
      'hey': 'Olá,', 'checkTasksToday': 'Verifique suas tarefas de hoje',
      'searchTasks': 'Buscar tarefas…', 'myProjects': 'Meus projetos',
      'seeAll': 'Ver tudo', 'myTasks': 'Minhas tarefas',
      'noTasksAssigned': 'Sem tarefas atribuídas',
      'noTasksAssignedDesc': 'As tarefas atribuídas a você aparecerão aqui',
      'createFirstProject': 'Crie seu primeiro projeto',
      'tapToStart': 'Toque para começar',
      'firstCreateProject': 'Crie um projeto primeiro',
      'selectProject': 'Selecionar projeto',
      'projects': 'Projetos', 'newProject': 'Novo projeto',
      'projectName': 'Nome do projeto',
      'descriptionOptional': 'Descrição (opcional)',
      'addMembers': 'Adicionar membros',
      'noUsersAvailable': 'Nenhum usuário disponível',
      'create': 'Criar', 'noProjects': 'Sem projetos',
      'createFirstProjectDesc': 'Crie seu primeiro projeto',
      'calendar': 'Calendário',
      'noTasksForDay': 'Sem tarefas para este dia',
      'tasksFor': 'Tarefas para',
      'profileData': 'Dados do perfil', 'edit': 'Editar',
      'cancel': 'Cancelar', 'saveChanges': 'Salvar alterações',
      'username': 'Nome de usuário', 'email': 'E-mail',
      'administrator': 'Administrador', 'profileUpdated': 'Perfil atualizado',
      'errorSaving': 'Erro ao salvar', 'notifications': 'Notificações',
      'notifMentions': 'Menções',
      'notifMentionsDesc': 'Quando alguém te mencionar',
      'notifNewTasks': 'Novas tarefas',
      'notifNewTasksDesc': 'Quando você for atribuído a uma tarefa',
      'notifStatusChanges': 'Mudanças de status',
      'notifStatusChangesDesc': 'Quando o status de uma tarefa mudar',
      'language': 'Idioma', 'selectLanguage': 'Selecionar idioma',
      'changePassword': 'Alterar senha', 'logout': 'Sair',
    },
    // ── Русский ──────────────────────────────────────────────────────────────
    'ru': {
      'navHome': 'Главная', 'navProjects': 'Проекты',
      'navCalendar': 'Календарь', 'navAccount': 'Аккаунт',
      'hey': 'Привет,',
      'checkTasksToday': 'Проверьте свои задачи на сегодня',
      'searchTasks': 'Поиск задач…', 'myProjects': 'Мои проекты',
      'seeAll': 'Смотреть все', 'myTasks': 'Мои задачи',
      'noTasksAssigned': 'Нет назначенных задач',
      'noTasksAssignedDesc': 'Задачи, назначенные вам, появятся здесь',
      'createFirstProject': 'Создайте первый проект',
      'tapToStart': 'Нажмите для начала',
      'firstCreateProject': 'Сначала создайте проект',
      'selectProject': 'Выбрать проект',
      'projects': 'Проекты', 'newProject': 'Новый проект',
      'projectName': 'Название проекта',
      'descriptionOptional': 'Описание (необязательно)',
      'addMembers': 'Добавить участников',
      'noUsersAvailable': 'Нет доступных пользователей',
      'create': 'Создать', 'noProjects': 'Нет проектов',
      'createFirstProjectDesc': 'Создайте свой первый проект',
      'calendar': 'Календарь',
      'noTasksForDay': 'Нет задач на этот день',
      'tasksFor': 'Задачи на',
      'profileData': 'Данные профиля', 'edit': 'Редактировать',
      'cancel': 'Отмена', 'saveChanges': 'Сохранить изменения',
      'username': 'Имя пользователя', 'email': 'Электронная почта',
      'administrator': 'Администратор', 'profileUpdated': 'Профиль обновлён',
      'errorSaving': 'Ошибка сохранения',
      'notifications': 'Уведомления', 'notifMentions': 'Упоминания',
      'notifMentionsDesc': 'Когда кто-то упомянет вас',
      'notifNewTasks': 'Новые задачи',
      'notifNewTasksDesc': 'Когда вам назначат задачу',
      'notifStatusChanges': 'Изменения статуса',
      'notifStatusChangesDesc': 'Когда изменится статус задачи',
      'language': 'Язык', 'selectLanguage': 'Выбрать язык',
      'changePassword': 'Сменить пароль', 'logout': 'Выйти',
    },
    // ── 中文 ──────────────────────────────────────────────────────────────────
    'zh': {
      'navHome': '主页', 'navProjects': '项目',
      'navCalendar': '日历', 'navAccount': '账户',
      'hey': '嗨,', 'checkTasksToday': '查看今天的任务',
      'searchTasks': '搜索任务…', 'myProjects': '我的项目',
      'seeAll': '查看全部', 'myTasks': '我的任务',
      'noTasksAssigned': '没有分配的任务',
      'noTasksAssignedDesc': '分配给您的任务将显示在这里',
      'createFirstProject': '创建第一个项目',
      'tapToStart': '点击开始', 'firstCreateProject': '请先创建项目',
      'selectProject': '选择项目',
      'projects': '项目', 'newProject': '新项目',
      'projectName': '项目名称', 'descriptionOptional': '描述（可选）',
      'addMembers': '添加成员', 'noUsersAvailable': '没有可用用户',
      'create': '创建', 'noProjects': '没有项目',
      'createFirstProjectDesc': '创建您的第一个项目',
      'calendar': '日历', 'noTasksForDay': '今天没有任务',
      'tasksFor': '任务：',
      'profileData': '个人资料', 'edit': '编辑', 'cancel': '取消',
      'saveChanges': '保存更改', 'username': '用户名', 'email': '电子邮件',
      'administrator': '管理员', 'profileUpdated': '个人资料已更新',
      'errorSaving': '保存失败', 'notifications': '通知',
      'notifMentions': '提及', 'notifMentionsDesc': '当有人提及您时',
      'notifNewTasks': '新任务', 'notifNewTasksDesc': '当您被分配到任务时',
      'notifStatusChanges': '状态变更',
      'notifStatusChangesDesc': '当任务状态改变时',
      'language': '语言', 'selectLanguage': '选择语言',
      'changePassword': '修改密码', 'logout': '退出登录',
    },
    // ── 日本語 ────────────────────────────────────────────────────────────────
    'ja': {
      'navHome': 'ホーム', 'navProjects': 'プロジェクト',
      'navCalendar': 'カレンダー', 'navAccount': 'アカウント',
      'hey': 'こんにちは,',
      'checkTasksToday': '今日のタスクを確認しましょう',
      'searchTasks': 'タスクを検索…',
      'myProjects': 'マイプロジェクト',
      'seeAll': 'すべて見る', 'myTasks': 'マイタスク',
      'noTasksAssigned': '割り当てられたタスクがありません',
      'noTasksAssignedDesc': '割り当てられたタスクがここに表示されます',
      'createFirstProject': '最初のプロジェクトを作成',
      'tapToStart': 'タップして開始',
      'firstCreateProject': '最初にプロジェクトを作成してください',
      'selectProject': 'プロジェクトを選択',
      'projects': 'プロジェクト', 'newProject': '新しいプロジェクト',
      'projectName': 'プロジェクト名', 'descriptionOptional': '説明（任意）',
      'addMembers': 'メンバーを追加',
      'noUsersAvailable': '利用可能なユーザーがいません',
      'create': '作成', 'noProjects': 'プロジェクトがありません',
      'createFirstProjectDesc': '最初のプロジェクトを作成してください',
      'calendar': 'カレンダー',
      'noTasksForDay': 'この日のタスクがありません',
      'tasksFor': 'タスク：',
      'profileData': 'プロフィール', 'edit': '編集',
      'cancel': 'キャンセル', 'saveChanges': '変更を保存',
      'username': 'ユーザー名', 'email': 'メールアドレス',
      'administrator': '管理者',
      'profileUpdated': 'プロフィールが更新されました',
      'errorSaving': '保存エラー', 'notifications': '通知',
      'notifMentions': 'メンション',
      'notifMentionsDesc': '誰かがあなたをメンションしたとき',
      'notifNewTasks': '新しいタスク',
      'notifNewTasksDesc': 'タスクに割り当てられたとき',
      'notifStatusChanges': 'ステータス変更',
      'notifStatusChangesDesc': 'タスクのステータスが変わったとき',
      'language': '言語', 'selectLanguage': '言語を選択',
      'changePassword': 'パスワードを変更', 'logout': 'ログアウト',
    },
    // ── 한국어 ────────────────────────────────────────────────────────────────
    'ko': {
      'navHome': '홈', 'navProjects': '프로젝트',
      'navCalendar': '캘린더', 'navAccount': '계정',
      'hey': '안녕,', 'checkTasksToday': '오늘의 작업을 확인하세요',
      'searchTasks': '작업 검색…', 'myProjects': '내 프로젝트',
      'seeAll': '전체 보기', 'myTasks': '내 작업',
      'noTasksAssigned': '할당된 작업 없음',
      'noTasksAssignedDesc': '나에게 할당된 작업이 여기에 표시됩니다',
      'createFirstProject': '첫 번째 프로젝트 만들기',
      'tapToStart': '탭하여 시작',
      'firstCreateProject': '먼저 프로젝트를 만드세요',
      'selectProject': '프로젝트 선택',
      'projects': '프로젝트', 'newProject': '새 프로젝트',
      'projectName': '프로젝트 이름',
      'descriptionOptional': '설명 (선택 사항)',
      'addMembers': '멤버 추가', 'noUsersAvailable': '사용 가능한 사용자 없음',
      'create': '만들기', 'noProjects': '프로젝트 없음',
      'createFirstProjectDesc': '첫 번째 프로젝트를 만드세요',
      'calendar': '캘린더', 'noTasksForDay': '이 날의 작업 없음',
      'tasksFor': '작업：',
      'profileData': '프로필 데이터', 'edit': '편집', 'cancel': '취소',
      'saveChanges': '변경사항 저장', 'username': '사용자 이름',
      'email': '이메일', 'administrator': '관리자',
      'profileUpdated': '프로필이 업데이트되었습니다',
      'errorSaving': '저장 오류', 'notifications': '알림',
      'notifMentions': '멘션', 'notifMentionsDesc': '누군가 나를 언급할 때',
      'notifNewTasks': '새 작업', 'notifNewTasksDesc': '작업에 할당될 때',
      'notifStatusChanges': '상태 변경',
      'notifStatusChangesDesc': '작업 상태가 변경될 때',
      'language': '언어', 'selectLanguage': '언어 선택',
      'changePassword': '비밀번호 변경', 'logout': '로그아웃',
    },
    // ── العربية ───────────────────────────────────────────────────────────────
    'ar': {
      'navHome': 'الرئيسية', 'navProjects': 'المشاريع',
      'navCalendar': 'التقويم', 'navAccount': 'الحساب',
      'hey': 'مرحباً,', 'checkTasksToday': 'تحقق من مهامك اليوم',
      'searchTasks': 'البحث عن المهام…', 'myProjects': 'مشاريعي',
      'seeAll': 'رؤية الكل', 'myTasks': 'مهامي',
      'noTasksAssigned': 'لا توجد مهام مخصصة',
      'noTasksAssignedDesc': 'ستظهر المهام المخصصة لك هنا',
      'createFirstProject': 'إنشاء أول مشروع',
      'tapToStart': 'اضغط للبدء',
      'firstCreateProject': 'أنشئ مشروعاً أولاً',
      'selectProject': 'اختر المشروع',
      'projects': 'المشاريع', 'newProject': 'مشروع جديد',
      'projectName': 'اسم المشروع',
      'descriptionOptional': 'الوصف (اختياري)',
      'addMembers': 'إضافة أعضاء',
      'noUsersAvailable': 'لا يوجد مستخدمون متاحون',
      'create': 'إنشاء', 'noProjects': 'لا توجد مشاريع',
      'createFirstProjectDesc': 'أنشئ مشروعك الأول',
      'calendar': 'التقويم',
      'noTasksForDay': 'لا توجد مهام لهذا اليوم',
      'tasksFor': 'مهام:',
      'profileData': 'بيانات الملف الشخصي', 'edit': 'تعديل',
      'cancel': 'إلغاء', 'saveChanges': 'حفظ التغييرات',
      'username': 'اسم المستخدم', 'email': 'البريد الإلكتروني',
      'administrator': 'مسؤول', 'profileUpdated': 'تم تحديث الملف الشخصي',
      'errorSaving': 'خطأ في الحفظ', 'notifications': 'الإشعارات',
      'notifMentions': 'الإشارات',
      'notifMentionsDesc': 'عند إشارة أحدهم إليك',
      'notifNewTasks': 'مهام جديدة', 'notifNewTasksDesc': 'عند تعيينك لمهمة',
      'notifStatusChanges': 'تغييرات الحالة',
      'notifStatusChangesDesc': 'عند تغيير حالة المهمة',
      'language': 'اللغة', 'selectLanguage': 'اختر اللغة',
      'changePassword': 'تغيير كلمة المرور', 'logout': 'تسجيل الخروج',
    },
    // ── हिन्दी ────────────────────────────────────────────────────────────────
    'hi': {
      'navHome': 'होम', 'navProjects': 'परियोजनाएं',
      'navCalendar': 'कैलेंडर', 'navAccount': 'खाता',
      'hey': 'नमस्ते,', 'checkTasksToday': 'आज के कार्य देखें',
      'searchTasks': 'कार्य खोजें…', 'myProjects': 'मेरी परियोजनाएं',
      'seeAll': 'सभी देखें', 'myTasks': 'मेरे कार्य',
      'noTasksAssigned': 'कोई नियत कार्य नहीं',
      'noTasksAssignedDesc': 'आपको सौंपे गए कार्य यहाँ दिखेंगे',
      'createFirstProject': 'पहली परियोजना बनाएं',
      'tapToStart': 'शुरू करने के लिए टैप करें',
      'firstCreateProject': 'पहले एक परियोजना बनाएं',
      'selectProject': 'परियोजना चुनें',
      'projects': 'परियोजनाएं', 'newProject': 'नई परियोजना',
      'projectName': 'परियोजना का नाम',
      'descriptionOptional': 'विवरण (वैकल्पिक)',
      'addMembers': 'सदस्य जोड़ें',
      'noUsersAvailable': 'कोई उपयोगकर्ता उपलब्ध नहीं',
      'create': 'बनाएं', 'noProjects': 'कोई परियोजना नहीं',
      'createFirstProjectDesc': 'अपनी पहली परियोजना बनाएं',
      'calendar': 'कैलेंडर',
      'noTasksForDay': 'इस दिन के लिए कोई कार्य नहीं',
      'tasksFor': 'कार्य:',
      'profileData': 'प्रोफ़ाइल डेटा', 'edit': 'संपादित करें',
      'cancel': 'रद्द करें', 'saveChanges': 'परिवर्तन सहेजें',
      'username': 'उपयोगकर्ता नाम', 'email': 'ईमेल',
      'administrator': 'व्यवस्थापक',
      'profileUpdated': 'प्रोफ़ाइल अपडेट की गई',
      'errorSaving': 'सहेजने में त्रुटि', 'notifications': 'सूचनाएं',
      'notifMentions': 'उल्लेख',
      'notifMentionsDesc': 'जब कोई आपका उल्लेख करे',
      'notifNewTasks': 'नए कार्य',
      'notifNewTasksDesc': 'जब आपको कोई कार्य सौंपा जाए',
      'notifStatusChanges': 'स्थिति परिवर्तन',
      'notifStatusChangesDesc': 'जब किसी कार्य की स्थिति बदले',
      'language': 'भाषा', 'selectLanguage': 'भाषा चुनें',
      'changePassword': 'पासवर्ड बदलें', 'logout': 'लॉग आउट',
    },
    // ── Türkçe ───────────────────────────────────────────────────────────────
    'tr': {
      'navHome': 'Ana Sayfa', 'navProjects': 'Projeler',
      'navCalendar': 'Takvim', 'navAccount': 'Hesap',
      'hey': 'Merhaba,',
      'checkTasksToday': 'Bugünkü görevlerinizi kontrol edin',
      'searchTasks': 'Görev ara…', 'myProjects': 'Projelerim',
      'seeAll': 'Tümünü gör', 'myTasks': 'Görevlerim',
      'noTasksAssigned': 'Atanmış görev yok',
      'noTasksAssignedDesc': 'Size atanan görevler burada görünecek',
      'createFirstProject': 'İlk projeyi oluştur',
      'tapToStart': 'Başlamak için dokunun',
      'firstCreateProject': 'Önce bir proje oluşturun',
      'selectProject': 'Proje seçin',
      'projects': 'Projeler', 'newProject': 'Yeni proje',
      'projectName': 'Proje adı',
      'descriptionOptional': 'Açıklama (isteğe bağlı)',
      'addMembers': 'Üye ekle',
      'noUsersAvailable': 'Kullanılabilir kullanıcı yok',
      'create': 'Oluştur', 'noProjects': 'Proje yok',
      'createFirstProjectDesc': 'İlk projenizi oluşturun',
      'calendar': 'Takvim', 'noTasksForDay': 'Bu gün için görev yok',
      'tasksFor': 'Görevler:',
      'profileData': 'Profil Verileri', 'edit': 'Düzenle',
      'cancel': 'İptal', 'saveChanges': 'Değişiklikleri Kaydet',
      'username': 'Kullanıcı Adı', 'email': 'E-posta',
      'administrator': 'Yönetici', 'profileUpdated': 'Profil güncellendi',
      'errorSaving': 'Kaydetme hatası', 'notifications': 'Bildirimler',
      'notifMentions': 'Bahsetmeler',
      'notifMentionsDesc': 'Biri sizi bahsettiğinde',
      'notifNewTasks': 'Yeni Görevler',
      'notifNewTasksDesc': 'Bir göreve atandığınızda',
      'notifStatusChanges': 'Durum Değişiklikleri',
      'notifStatusChangesDesc': 'Bir görevin durumu değiştiğinde',
      'language': 'Dil', 'selectLanguage': 'Dil Seçin',
      'changePassword': 'Şifre Değiştir', 'logout': 'Çıkış Yap',
    },
    // ── Nederlands ───────────────────────────────────────────────────────────
    'nl': {
      'navHome': 'Home', 'navProjects': 'Projecten',
      'navCalendar': 'Kalender', 'navAccount': 'Account',
      'hey': 'Hoi,', 'checkTasksToday': 'Bekijk je taken voor vandaag',
      'searchTasks': 'Taken zoeken…', 'myProjects': 'Mijn projecten',
      'seeAll': 'Alles zien', 'myTasks': 'Mijn taken',
      'noTasksAssigned': 'Geen toegewezen taken',
      'noTasksAssignedDesc': 'Taken die aan jou zijn toegewezen verschijnen hier',
      'createFirstProject': 'Maak je eerste project',
      'tapToStart': 'Tik om te beginnen',
      'firstCreateProject': 'Maak eerst een project',
      'selectProject': 'Selecteer project',
      'projects': 'Projecten', 'newProject': 'Nieuw project',
      'projectName': 'Projectnaam',
      'descriptionOptional': 'Beschrijving (optioneel)',
      'addMembers': 'Leden toevoegen',
      'noUsersAvailable': 'Geen gebruikers beschikbaar',
      'create': 'Aanmaken', 'noProjects': 'Geen projecten',
      'createFirstProjectDesc': 'Maak je eerste project',
      'calendar': 'Kalender', 'noTasksForDay': 'Geen taken voor deze dag',
      'tasksFor': 'Taken voor',
      'profileData': 'Profielgegevens', 'edit': 'Bewerken',
      'cancel': 'Annuleren', 'saveChanges': 'Wijzigingen opslaan',
      'username': 'Gebruikersnaam', 'email': 'E-mail',
      'administrator': 'Beheerder', 'profileUpdated': 'Profiel bijgewerkt',
      'errorSaving': 'Fout bij opslaan', 'notifications': 'Meldingen',
      'notifMentions': 'Vermeldingen',
      'notifMentionsDesc': 'Wanneer iemand je vermeldt',
      'notifNewTasks': 'Nieuwe taken',
      'notifNewTasksDesc': 'Wanneer je aan een taak wordt toegewezen',
      'notifStatusChanges': 'Statuswijzigingen',
      'notifStatusChangesDesc': 'Wanneer de status van een taak verandert',
      'language': 'Taal', 'selectLanguage': 'Taal selecteren',
      'changePassword': 'Wachtwoord wijzigen', 'logout': 'Uitloggen',
    },
  };
}
