name: Django CI (Docker)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Build obrazu
        run: docker build -t my-django-app .
